# Generated by Django 4.2 on 2023-05-03 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Назва')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Кількість')),
                ('unit', models.CharField(choices=[('kg', 'кг.'), ('l', 'л.'), ('p', 'шт.')], default='kg', max_length=2, verbose_name='Одиниця вимірювання')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата редагування')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Відредагував')),
            ],
            options={
                'verbose_name': 'Інгрідієнт',
                'verbose_name_plural': 'Інгрідієнти',
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=recipes.models.Recipe.get_preview_path, verbose_name="Фото-прев'ю")),
                ('folder_path', models.FilePathField(blank=True, max_length=260, null=True, verbose_name='Шлях до папки з фото')),
                ('title', models.CharField(max_length=128, verbose_name='Назва')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Детальний рецепт')),
                ('cooking_time', models.CharField(max_length=32, verbose_name='Час приготування')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата редагування')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вартість')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('likes', models.ManyToManyField(related_name='like_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Уподобали')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Відредагував')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепти',
                'db_table': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Оцінка')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'db_table': 'StarRatings',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Кількість (кг./л./шт.)')),
                ('worth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вартість')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Інгрідієнт')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Інгрідієнт',
                'verbose_name_plural': 'Інгрідієнти для страви',
                'db_table': 'IngredientsInRecipes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('content', models.TextField(max_length=2000, verbose_name='Вміст')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Коментар до рецепту')),
                ('сommented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'db_table': 'Comments',
            },
        ),
    ]
