# Generated by Django 4.2 on 2023-04-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_author_recipe_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Інгрідієнт'),
            preserve_default=False,
        ),
    ]
