# Generated by Django 4.2 on 2023-04-05 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='like_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
