# Generated by Django 4.2 on 2023-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Вартість'),
        ),
    ]
