# Generated by Django 4.2 on 2023-04-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total',
        ),
    ]
