# Generated by Django 4.2 on 2023-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total',
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вартість'),
        ),
    ]
