# Generated by Django 4.2 on 2023-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipe_total_recipe_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='folder_path',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Шлях до папки'),
        ),
    ]
