# Generated by Django 4.2 on 2023-04-28 20:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preview',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='<django.db.models.fields.CharField>/cover.webp', verbose_name="Фото-прев'ю"),
        ),
    ]
