# Generated by Django 4.2 on 2023-04-28 21:31

from django.db import migrations
import django_resized.forms
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipe_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=recipes.models.Recipe.get_preview_path, verbose_name="Фото-прев'ю"),
        ),
    ]
