# Generated by Django 4.2 on 2023-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='folder_path',
            field=models.FileField(blank=True, max_length=260, null=True, upload_to='', verbose_name='Шлях до папки'),
        ),
    ]
